create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  student_name text not null,
  school text not null,
  level text not null,
  course_format text not null default 'Cours collectif mini groupe',
  whatsapp text not null,
  city text not null,
  status text not null default 'pending',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  confirmed_at timestamptz
);

create table if not exists public.pricing (
  level text primary key,
  price integer not null,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.site_settings (
  id integer primary key,
  center_name text not null,
  center_address text not null,
  maps_url text not null,
  format_pricing_json text not null default '{}',
  course_formats_json text not null,
  updated_at timestamptz not null default timezone('utc', now()),
  constraint site_settings_single_row check (id = 1)
);

create index if not exists reservations_created_at_idx on public.reservations (created_at desc);
create index if not exists reservations_status_idx on public.reservations (status);

alter table public.admins enable row level security;
alter table public.reservations enable row level security;
alter table public.pricing enable row level security;
alter table public.site_settings enable row level security;
